#!/bin/bash
# ApplyPilot Chrome Login Setup for Railway

echo "=== ApplyPilot Chrome Login Setup (Railway) ==="
echo ""
echo "This setup uses Playwright for browser automation on Railway."
echo ""
echo "=== Method 1: Web-based Login (Easiest) ==="
echo ""
echo "1. Deploy to Railway and open your service URL"
echo "2. Navigate to: https://your-service.railway.app/chrome/devtools"
echo "3. Use the web interface to log in to LinkedIn and Indeed"
echo "4. Your session will be saved in /data/browser-profile"
echo ""
echo "=== Method 2: Railway CLI ==="
echo ""
echo "1. Install Railway CLI: npm install -g @railway/cli"
echo "2. Login: railway login"
echo "3. Link to your project: railway link"
echo "4. Open browser-based login: railway open"
echo "5. Navigate to /chrome/devtools endpoint"
echo ""
echo "=== Method 3: Direct API Calls ==="
echo ""
echo "1. Start the browser:"
echo "   curl -X POST https://your-service.railway.app/chrome/start"
echo ""
echo "2. Navigate to LinkedIn:"
echo "   curl -X POST https://your-service.railway.app/chrome/navigate \\"
echo "        -H 'Content-Type: application/json' \\"
echo "        -d '{\"url\": \"https://www.linkedin.com/login\"}'"
echo ""
echo "3. Use /chrome/devtools to complete login"
echo ""
echo "=== Verifying Your Session ==="
echo ""
echo "Check browser status:"
echo "   curl https://your-service.railway.app/chrome/status"
echo ""
echo "View dashboard:"
echo "   curl https://your-service.railway.app/"
echo ""
echo "=== Important Notes ==="
echo ""
echo "- Sessions persist in Railway's /data PVC"
echo "- You only need to log in once per deployment"
echo "- Playwright runs headless on Railway"
echo "- The /chrome/devtools page provides a web-based login interface"
echo ""
echo "For more information, see: docs/RAILWAY_CHROME.md"
echo ""
