#!/bin/bash
# ApplyPilot Chrome Login Setup

echo "=== ApplyPilot Chrome Login Setup ==="
echo ""
echo "Chrome is running on Railway at port 9222"
echo ""
echo "To log in to LinkedIn/Indeed:"
echo ""
echo "1. Open Railway dashboard to get SSH string:"
echo "   railway open"
echo ""
echo "2. Click on 'comfortable-flow' service → 'Connect' button"
echo ""
echo "3. Copy the SSH command and add port forwarding:"
echo "   ssh -p 443 -L 9222:localhost:9222 railway@..."
echo ""
echo "4. Keep SSH terminal open, then open:"
echo "   chrome://inspect"
echo ""
echo "5. Add target: localhost:9222"
echo ""
echo "6. Click 'inspect' and in the console run:"
echo "   window.location = 'https://www.linkedin.com/login'"
echo "   # Log in, then:"
echo "   window.location = 'https://secure.indeed.com/account/login'"
echo "   # Log in"
echo ""
echo "Your session will be saved!"
echo ""
echo "Dashboard: https://comfortable-flow-production.up.railway.app"
